### ISSUE TITLE
cannot run the ceph plugin

### ISSUE THREAD

**Issue by myandpr** [djmaze/docker-ceph-rbd#1]
when I run the command "docker plugin install mazzolino/ceph-rbd", a error occurs:

Error response from daemon: rpc error: code = 2 desc = oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/sys/bus/rbd\\\" to rootfs \\\"/var/lib/docker/plugins/8aec1022ddeb69c56627923f22f97310c26d8105f2fbf6a75b45368c1ce8dd1a/rootfs\\\" at \\\"/host/sys/bus/rbd\\\" caused \\\"stat /sys/bus/rbd: no such file or directory\\\"\""

I change my machine,the error still occurs.

The version is as follows:
centos 7.3.1611
docker 17.06.2-ce
go1.8.3

**Comment by djmaze** [comment]
@myandpr Try running `modprobe rbd` on your system beforehand.

Sorry for the _very late_ answer!
